/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RegisterBodySchema {
  cc?: string;
  phone: string;
  code: string;
  firstName: string;
  lastName: string;
  cpf: string;
  birth: string;
  terms: boolean;
  credential?: string;
}
