/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateRideBodySchema {
  route: Route;
  /**
   * The ride type
   *  * 1 = Normal
   *  * 2 = VIG
   */
  type: 1 | 2;
  /**
   * Payment method
   *  * 1 = Money
   *  * 2 = Credit Card
   */
  payMethod: 1 | 2;
}
export interface Route {
  start: Point;
  waypoints?: Point[];
  end: Point;
  /**
   * Encoded path polyline
   */
  path: string;
  distance: number;
}
export interface Point {
  /**
   * Latitude and longitude
   */
  coord: [number, number];
  /**
   * Primary title
   */
  primary: string;
  /**
   * Secondary title
   */
  secondary: string;
  /**
   * Slug name of district
   */
  district: string;
}
