/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PricesStatusResponse = {
  /**
   * Ride type:
   *  * 1 = Normal
   *  * 2 = VIG
   */
  type: 1 | 2;
  perKilometer?: number;
  perMinute?: number;
  /**
   * Additional cost per kilometer in rides bigger than 10 kilometers
   */
  kilometerMultipler?: number;
  /**
   * Additional cost per minute in rides bigger than 10 kilometers
   */
  minuteMultipler?: number;
  /**
   * Additional cost per kilometer in rides out of business time
   */
  overBusinessTimeKmAdd?: number;
  /**
   * Additional cost per minute in rides out of business time
   */
  overBusinessTimeMinuteAdd?: number;
}[];
