/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PricesStatusResponse = {
  /**
   * Ride type:
   *  * 1 = Normal
   *  * 2 = VIG
   */
  type: 1 | 2;
  values: {
    per_kilometer: number;
    per_minute: number;
    /**
     * Additional cost per kilometer in rides bigger than 10 kilometers
     */
    kilometer_multipler: number;
    /**
     * Additional cost per minute in rides bigger than 10 kilometers
     */
    minute_multipler: number;
    /**
     * Additional cost per kilometer in rides out of business time
     */
    over_business_time_km_add: number;
    /**
     * Additional cost per minute in rides out of business time
     */
    over_business_time_minute_add: number;
  };
}[];
