version: "3"

x-gxweb-dev: &gxweb-dev
  build:
    context: ../
    dockerfile: ./server/Dockerfile
  volumes:
    - .:/usr/src/app
  networks:
    - gxnet
  environment:
    NODE_ENV: development
    DATABASE_URI: mongodb://gx-mongo:27017/
    REDIS_URI: redis://gx-redis:6379/

services:
  gx-webservices:
    <<: *gxweb-dev
    depends_on:
      - gx-mongo
      - gx-redis
    container_name: webservices
    command: npm run start:gateway:debug
    ports:
      - "3000:3000"
      - "9228:9228"

  #  gx-ridesflows:
  #    <<: *gxweb-dev
  #    depends_on:
  #      - gx-mongo
  #      - gx-redis
  #    container_name: gx-rides-flows
  #    command: npm run start:rides-flows:debug
  #    ports:
  #      - "3001:3001"
  #      - "9229:9229"

  gx-mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_DATABASE: config
    networks:
      - gxnet

  gx-redis:
    image: redis
    restart: always
    networks:
      - gxnet

#  test:
#    <<: *gxweb-dev
#    container_name: gx-testing
#    depends_on:
#      - gx-mongo
#      - gx-redis
#    command: npm run test -- --force-exit --bail

volumes:
  mongo:

networks:
  gxnet:
    driver: bridge
