version: "3"
services:
  gx-common:
    build:
      context: ../
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/usr/src/app
    networks:
      - gxnet
    environment:
      NODE_ENV: development
      DATABASE_URI: mongodb://gx-mongo:27017/config
      REDIS_URI: redis://gx-redis:6379/0
    depends_on:
      - gx-mongo
      - gx-redis
    container_name: gx-common
    command: npm run start:debug & npm run start:debug -- rides-flows
    ports:
      - 3000:3000
      - 3001:3001
      - 9229:9229

  gx-mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_DATABASE: config
    networks:
      - gxnet

  gx-redis:
    image: redis
    restart: always
    networks:
      - gxnet

#  e2e-testing:
#    <<: *standard-webservice
#    command: npm run test -- --group="e2e"

volumes:
  mongo:

networks:
  gxnet:
    driver: bridge
