version: "3"
x-gxweb-dev: &gxweb-dev
  build:
    context: .
    target: development
  volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
  networks:
    - gxnet
  environment:
    NODE_ENV: development
    DATABASE_URI: mongodb://gx-mongo:27017/config
    REDIS_URI: redis://gx-redis:6379/0
  depends_on:
    - gx-mongo
    - gx-redis

services:
  gx-common:
    <<: *gxweb-dev
    container_name: gx-common
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229

  gx-rides-flows:
    <<: *gxweb-dev
    container_name: gx-rides-flows
    command: "npm run start:debug rides-flows" # pm2 start dist/run/main.js -i max -- --max_old_space_size=4096
    ports:
      - 3001:3001
      - 9227:9227

  gx-mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_DATABASE: config
      MONGO_REPLICA_SET_NAME: gxmongoreplica
    networks:
      - gxnet

  gx-redis:
    image: redis
    restart: always
    networks:
      - gxnet

#  e2e-testing:
#    <<: *standard-webservice
#    command: npm run test -- --group="e2e"

volumes:
  mongo:

networks:
  gxnet:
