import location, { Location } from "../common/location";
import rideTypes, { RideTypes } from "../common/ride-types";

/**
 * Position event schema
 */
export type OfferRequest = {
  id: string;
  voyagers: string[];
  /**
   * Start point of the ride
   */
  start: Location;
  waypoint?: Location[];
  /**
   * End point of the ride
   */
  end: Location;
  /**
   * Ride types
   * * 1 = Normal
   * * 2 = VIG - Very important gx
   */
  type: RideTypes;
  /**
   * Distance in meters
   */
  distance: number;
  /**
   * Paymethod
   * * 1 = Money
   * * 2 = Credit card
   */
  payMethod: 1 | 2;
  /**
   * Ride calculated price
   */
  amount: number;
  /**
   * The route generated by user client and sent to routes service,
   * to calculate the ride price, avoiding mal intent price changing
   * and applying, if exist, any user payment pendency.
   */
  routeID: string;
};

export type ServerProps = {
  /**
   * Requester socket id
   */
  requesterSocketId: string;
  /**
   * To improve performance of the riders iteration.
   *
   * Drivers that are too distante, not eligible, that hit the
   * response timeout or refuse the offer are added to this list
   * and skipped in the next iteration.
   */
  ignoreds: string[];
  /**
   * Timeout to rider response the offer
   */
  offerResponseTimeout: NodeJS.Timeout | null;
  /**
   * Send buffer, encoded offer object
   *
   * Perfomance improvement, to don't encode the object in each event emission
   */
  sendBuff: Buffer;
  /**
   * Offered
   *
   * Current offered driver
   */
  offeredTo: string | null;
  /**
   * Used to increase the distance ratio of match algorithm
   */
  trys: number;
};

export type OfferServer = OfferRequest & ServerProps;

const offer = {
  id: "string",
  start: location,
  waypoints: [location],
  end: location,
  type: rideTypes,
  distance: "uint16",
  payMethod: "uint8",
  amount: "uint16",
};

export const offerServer = {
  ...offer,
  ignoreds: ["string"],
  accepted: "boolean",
  routeSent: "boolean",
};

export default {
  id: 1,
  schema: offer,
};
