export const DEFAULT_ACK_TIMEOUT = 3000;

export enum SERVER_EVENTS {
  DISPATCHED_BROADCASTED_EVENT = "DISPATCHED_BROADCASTED_EVENT",
  DISPATCHED_SOCKET_EVENT = "DISPATCHED_SOCKET_EVENT",
  SOCKET_NODE_EVENT = "SOCKET_NODE_EVENT",
}
