export const NAMESPACES = {
  VOYAGER: 1,
  RIDER: 2,
};

export const MATCH_MAX_EXECUTION = 100;
export const MATCH_EXECUTION_INTERVAL = 1000; // 1 second

export const OFFER_DRIVER_OFFER_RESPONSE_TIMEOUT = 13000;
export const OFFER_ADDITIONAL_METERS_OVER_TRY = 200;
export const OFFER_INITIAL_DISTANCE_LIMIT = 1000;
export const OFFER_DISTANCE_LIMIT = 1800;
