export const NAMESPACES = {
  VOYAGER: 1,
  RIDER: 2,
};

export const OFFER_DRIVER_OFFER_RESPONSE_TIMEOUT = 13000;
export const OFFER_ADDITIONAL_METERS_OVER_TRY = 200;
export const OFFER_INITIAL_MAX_DISTANCE = 2000;
