name: Register Service

on:
  push:
    branches: [master, production]
    paths:
      - "services/register/**"

jobs:
  defaults:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build gx-http-service module
        run: npm pack ./packages/http-service
      - run: npm ci
      - run: npm lint
      - run: npm test -- --coverage
      - run: npm build
      - name: Initialize Google Cloud SDK
        if: github.ref == 'refs/heads/production'
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_variables: ${{ secrets.GAE_VARIABLES }}
          gae_config_path: "./services/register/app.yml"

      - name: Publish service to Google App Engine
        if: github.ref == 'refs/heads/production'
        run: |
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
