name: Register Service

on:
  push:
    branches: [master, beta, production]
    paths:
      - "services/register/**"

jobs:
  defaults:
    runs-on: ubuntu-latest
    env:
      working-directory: ./services/register
    steps:
      - uses: actions/checkout@v2
      - name: Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build gx-http-service module
        run: npm pack ./packages/http-service
      - name: Lint, test and build
        run: |
          npm ci
          npm lint
          npm test -- --coverage
          npm build
        working-directory: ${{env.working-directory}}
      - name: Initialize Google Cloud SDK
        if: ${{ github.ref == 'refs/heads/production' || github.ref == 'refs/heads/beta' }}
        uses: GX-mob/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_variables: ${{ secrets.GAE_VARIABLES }}
          gae_config_path: "./services/register/app.yml"

      - name: Publish service to Google App Engine
        if: ${{ github.ref == 'refs/heads/production' || github.ref == 'refs/heads/beta' }}
        run: |
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote
        working-directory: ${{env.working-directory}}
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        working-directory: ${{env.working-directory}}
